Update zh-hant.php
Toollabs/relgen pull request #7
Opened 2017-04-12 15:53 UTC by Taiwania

Full translated.

2017-04-12 15:57 UTC, Taiwania commented
......It's my first time to use GitHub. If I'm doing something wrong, please talk to me.

2017-04-12 16:19 UTC, Taiwania commented
Fixed: step 5/5 translated.

2017-04-14 14:56 UTC, Artoria2e5 requested changes
Almost good.

2017-04-14 14:56 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +  <body style="background: url('bg.png') no-repeat fixed right bottom; overflow:hidden;">
Asking for some `lang="zh-Hant"` here.

2017-04-14 14:56 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +      <h1>維基媒體 OTRS 釋出產生器 <small><a id="meta" tabindex="0" data-toggle="popover" data-placement="bottom" data-trigger="focus" data-content="created and maintained by <a href='//meta.wikimedia.org/wik
Use CJK parentheses. (after &copy;)

2017-04-14 14:56 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +      <h1>維基媒體 OTRS 釋出產生器 <small><a id="meta" tabindex="0" data-toggle="popover" data-placement="bottom" data-trigger="focus" data-content="created and maintained by <a href='//meta.wikimedia.org/wik
Focus text (created and maintained by) not translated.

2017-04-14 14:56 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +      <h1>維基媒體 OTRS 釋出產生器 <small><a id="meta" tabindex="0" data-toggle="popover" data-placement="bottom" data-trigger="focus" data-content="created and maintained by <a href='//meta.wikimedia.org/wik
Just out of curiosity, why all these `//` protocol-relative links? WMF is using HTTPS anyway...

2017-04-14 14:56 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +              <p class="text-danger">維基媒體 OTRS 不能接受您的釋出授權──請向<a href="//commons.wikimedia.org/wiki/Commons:OTRS#notch">該作品的著作權持有人聯繫</a>。</p>
Use two U+2014's (——) for Chinese em dash. See Wikipedia MOS and W3C CLREQ.

2017-04-14 14:56 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +            <p>在部分國家，由於有<a href="//commons.wikimedia.org/wiki/Commons:Freedom_of_panorama" target="_blank"><b>全景自由攝影</b></a>的例外，建築物或其他永久公開展示的作品可不用提供原始著作權持有者釋出許可。在美國，只有建築物不需要提供原始著作權持有者的許可。</p>
Disputing the interpretation of panorama, and the phrasing of the whole world here. Try "室外公共場合攝影之自由". (Freedom of photos in public outdoor spaces.)

2017-04-14 14:56 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +            <p>在部分國家，由於有<a href="//commons.wikimedia.org/wiki/Commons:Freedom_of_panorama" target="_blank"><b>全景自由攝影</b></a>的例外，建築物或其他永久公開展示的作品可不用提供原始著作權持有者釋出許可。在美國，只有建築物不需要提供原始著作權持有者的許可。</p>
See also https://commons.wikimedia.org/wiki/Commons:Freedom_of_panorama#Taiwan_.28Republic_of_China.29. You may want to add a note on this.

2017-04-14 14:56 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +            <p>我同意將上述提到的內容以下列自由授權釋出：</p>
My `zh-cmn` parser is parsing `授權` (license) as a verb modified by `自由` (freedom). Try `授權書`.

2017-04-14 14:56 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +                  <li><a onclick="$('#licensei').val('創用CC CC0 1.0 通用版'); $('#iawattr').hide();">創用CC CC0 1.0 通用版 (貢獻至公共領域)</a></li>
Parentheses. Not gonna label them all, so look for these yourself.

2017-04-14 14:56 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +                $p1s = "$name 是";
Disputing the space placement here. People using a `zh` form likely give Chinese names, therefore spaces should not be needed.

2017-04-14 14:56 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +                if (($s1 == "2") && (($rep == "") || ($auth == ""))) echo "<p class='text-danger'>錯誤：沒有填入著作權持有者與/或職權！</p>";
I believe taking the `or` (`或`) is good enough.

2017-04-14 14:56 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +        date_default_timezone_set("UTC");
Is this worthy of localization by the way?

2017-04-14 14:58 UTC, Artoria2e5 commented on i18n/zh-hant.php
> +      <h1>維基媒體 OTRS 釋出產生器 <small><a id="meta" tabindex="0" data-toggle="popover" data-placement="bottom" data-trigger="focus" data-content="created and maintained by <a href='//meta.wikimedia.org/wik
Try using `釋出書`/`釋出信` to show readers that you are talking about a letter.

2017-04-15 12:47 UTC, Taiwania commented on i18n/zh-hant.php
> +      <h1>維基媒體 OTRS 釋出產生器 <small><a id="meta" tabindex="0" data-toggle="popover" data-placement="bottom" data-trigger="focus" data-content="created and maintained by <a href='//meta.wikimedia.org/wik
Use `釋出授權信` maybe better. Prove it later.

2017-04-18 13:03 UTC, merged